#! /bin/sh

case "$1" in
  rebuild)
	echo "Rebuilding po files" >&2
  	../../../../bin/i18ndude rebuild-pot --pot locales/operun.media.pot --create operun.media .
	;;
  sync)
	echo "Syncing po files" >&2
	../../../../bin/i18ndude sync --pot locales/operun.media.pot locales/*/LC_MESSAGES/operun.media.po
	;;
  all)
	echo "Rebuilding po files" >&2
  	../../../../bin/i18ndude rebuild-pot --pot locales/operun.media.pot --create operun.media .
	echo "Syncing po files" >&2
	../../../../bin/i18ndude sync --pot locales/operun.media.pot locales/*/LC_MESSAGES/operun.media.po
	;;
  *)
	echo "Usage: $0 rebuild|sync|all" >&2
	exit 3
	;;
esac